export enum AppointmentStatusEnum {
  WAIT_LIST = 'WAIT_LIST',
  SCHEDULE = 'SCHEDULE',
  CONFIRM1 = 'CONFIRM1',
  CONFIRM2 = 'CONFIRM2',
  CHECK_IN = 'CHECK_IN',
  READY = 'READY',
  VISIT = 'VISIT',
  COMPLETE = 'COMPLETE',
  CANCELED = 'CANCELED',
  RELEASED = 'RELEASED',
  RESCHEDULED = 'RESCHEDULED',
}
