export enum AppointmentStatusEnum {
  WAIT_LIST = 'WAIT_LIST',
  SCHEDULE = 'SCHEDULE',
  CONFIRM1 = 'CONFIRM1',
  CONFIRM2 = 'CONFIRM2',
  CHECK_IN = 'CHECK_IN',
  READY = 'READY',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETE = 'COMPLETE',
  CANCELED = 'CANCELED',
}
