export enum AppointmentActionEnum {
  CANCEL = 'CANCEL',
  CHANGE_DATE = 'CHANGE_DATE',
  CHANGE_APPT_TYPE = 'CHANGE_APPT_TYPE',
  CHANGE_DOCTOR = 'CHANGE_DOCTOR',
  RESCHEDULE_APPT = 'RESCHEDULE_APPT',
}
