export enum AppointmentActionEnum {
  CANCEL = 'CANCEL',
  CHANGE_DATE = 'CHANGE_DATE',
  CHANGE_APPT_TYPE = 'CHANGE_APPT_TYPE',
  CHANGE_DOCTOR = 'CHANGE_DOCTOR',
  RESCHEDULE_APPT = 'RESCHEDULE_APPT',
  SCHEDULE = 'SCHEDULE',
  CONFIRM1 = 'CONFIRM1',
  CONFIRM2 = 'CONFIRM2',
  CHECK_IN = 'CHECK_IN',
  READY = 'READY',
  RELEASE_PATIENT = 'RELEASE_PATIENT',
}
