export enum CancelRescheduleReasonCode {
  CHANGE_DOCTOR = 'CHANGE_DOCTOR',
  DOCTOR_UNAVAILABLE = 'DOCTOR_UNAVAILABLE',
  NO_SHOW_UP = 'NO_SHOW_UP',
  ABORT_VISIT = 'ABORT_VISIT',
  PATIENT_CANNOT_MAKE_IT = 'PATIENT_CANNOT_MAKE_IT',
  RELEASE_PATIENT = 'RELEASE_PATIENT',
  OTHER = 'OTHER',
}
