export enum ErrorCodes {
  INVALID_INPUT = 'INVALID_INPUT',
  SERVER_ERROR = 'SERVER_ERROR',
  CONFLICTS = 'CONFLICTS',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  REQUEST_HAS_EXISTING_AAP = 'REQUEST_HAS_EXISTING_AAP', //Patient has an existing appointment
  APPT_REQUEST_HAS_EXIST = 'APPT_REQUEST_HAS_EXIST', //Cannot make additional requests to book an appointment if there is a pending request
}
